license: "FN7QGAIBA5GGSY3FNZZWKAP7QAAACAYBARCGC5DBAEFAAAIBKIA77AQAAEAVGAP7QIAAAAAK76AQKAIC76CAAAAA77377AAB76FXWITWMVZHG2LPNYRDUMRMEJSW2YLJNQRDUITPGR4XA52AMFVWS4TBOBXXOZLSMVSC4Y3PNURCYITDN5WXAYLOPERDUISBNNUXEYKQN53WK4TFMQRCYITTMVQXI4ZCHIZTALBCORUWK4RCHIRHGY3BNRSSELBCORZGSYLMEI5HI4TVMUWCEZLOMQRDUIRSGAZDILJRGAWTAN2UGE4DUNBTHIYDCWRCPUATCAQ3JHNB2P3VDTAVMIFOQO726VHPJGQWLEHHWQDRAG26PZ7NBT4B3VSXFGMM54FNHDI6PA5GAPIWAF6ACMICXXQ4YSTLYHPISHE5M6ZCFKNZ5FYDA7WUSJDZPP7SDM6NOFSHW27OONP6CRCBXEGMSZUWIUFEPOQIKAA="
subdomain: "ramiro.okteto.me"

api:
  replicaCount: 1

buildkit:
  replicaCount: 1
  persistence:
    enabled: true

frontend:
  replicaCount: 1

okteto-nginx:
  controller:
    replicaCount: 1

ingress-nginx:
  controller:
    replicaCount: 1
    extraArgs:
      default-ssl-certificate: $(POD_NAMESPACE)/okteto-letsencrypt
      
  defaultBackend:
    replicaCount: 1

publicOverride: ramiro.okteto.me

registry:
  replicaCount: 1
  storage:
    provider:
      gcp:
        enabled: true
        bucket: ramiro-okteto-me
        project: okteto-demo-sandboxes
        workloadIdentity:
          enabled: true
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: "ramiro-okteto-me@okteto-demo-sandboxes.iam.gserviceaccount.com"

telemetry:
  enabled: false

theme:
  logo: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE3MSIgdmlld0JveD0iMCAwIDE3MSAxNzEiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik04NS41IDE3MUMxMzIuNzIgMTcxIDE3MSAxMzIuNzIgMTcxIDg1LjVDMTcxIDM4LjI3OTcgMTMyLjcyIDAgODUuNSAwQzM4LjI3OTcgMCAwIDM4LjI3OTcgMCA4NS41QzAgMTMyLjcyIDM4LjI3OTcgMTcxIDg1LjUgMTcxWiIgZmlsbD0iIzAwRDFDQSIvPgo8cGF0aCBkPSJNNTUuNzYwOCA4NS41MDAxQzU1Ljc2MDggNjkuMjE5IDY5LjIxNDIgNTUuNzYxIDg2LjEzMjYgNTUuNzYxQzk1LjgwNDUgNTUuNzYxIDEwNC4zNzkgNjAuMTczMyAxMDkuOTM4IDY3LjAyOTdDMTEzLjI2MiA3MS4xMzA2IDExOS4yODIgNzEuNzYgMTIzLjM4MyA2OC40MzU0QzEyNy40ODQgNjUuMTEwOCAxMjguMTEzIDU5LjA5MTIgMTI0Ljc4OSA1NC45OTAyQzExNS43MTQgNDMuNzk2NyAxMDEuNzQ3IDM2LjY0MjkgODYuMTMyNiAzNi42NDI5QzU4Ljk0NDcgMzYuNjQyOSAzNi42NDI4IDU4LjM3MzcgMzYuNjQyOCA4NS41MDAxQzM2LjY0MjggMTEyLjYyNyA1OC45NDQ3IDEzNC4zNTcgODYuMTMyNiAxMzQuMzU3QzEwMS43NDcgMTM0LjM1NyAxMTUuNzE0IDEyNy4yMDMgMTI0Ljc4OSAxMTYuMDFDMTI4LjExMyAxMTEuOTA5IDEyNy40ODQgMTA1Ljg4OSAxMjMuMzgzIDEwMi41NjVDMTE5LjI4MiA5OS4yNDAyIDExMy4yNjIgOTkuODY5NSAxMDkuOTM4IDEwMy45N0MxMDQuMzc5IDExMC44MjcgOTUuODA0NSAxMTUuMjM5IDg2LjEzMjYgMTE1LjIzOUM2OS4yMTQyIDExNS4yMzkgNTUuNzYwOCAxMDEuNzgxIDU1Ljc2MDggODUuNTAwMVoiIGZpbGw9IiMxQTI2M0UiLz4KPHBhdGggZD0iTTEyNC43OTggOTUuMDU5MUMxMzAuMDc3IDk1LjA1OTEgMTM0LjM1NyA5MC43Nzk0IDEzNC4zNTcgODUuNTAwMUMxMzQuMzU3IDgwLjIyMDggMTMwLjA3NyA3NS45NDExIDEyNC43OTggNzUuOTQxMUMxMTkuNTE5IDc1Ljk0MTEgMTE1LjIzOSA4MC4yMjA4IDExNS4yMzkgODUuNTAwMUMxMTUuMjM5IDkwLjc3OTQgMTE5LjUxOSA5NS4wNTkxIDEyNC43OTggOTUuMDU5MVoiIGZpbGw9IiMxQTI2M0UiLz4KPC9zdmc+Cg==
  primary: \#EFF3F2
  secondary: \#000000

webhook:
  replicaCount: 1

wildcardCertificate:
  create: false
  name: okteto-letsencrypt

quotas:
  limitranges:
    limits:
      enabled: false