apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ramiro-okteto-enterprise
  namespace: okteto
spec:
  acme:
    email: ramiro@okteto.com
    privateKeySecretRef:
      name: ramiro-okteto-enterprise-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: vast-watch-300207
          serviceAccountSecretRef:
            key: key
            name: okteto-registry-secret